frameworks:
- ["norec", "eng"]

encoder: /cluster/projects/nn9851k/models/xlm-roberta-base
n_layers: 2
query_length: 2
balance_loss_weights: false
decoder_learning_rate: 3.0e-4
encoder_learning_rate: 1.0e-5            # initial encoder learning rate
label_smoothing: 0.0
encoder_delay_steps: 1000
warmup_steps: 2000
char_embedding: false
dropout_word: 0.0
focal: true
hidden_size_edge_presence: 128
batch_size: 16