dist: trusty
sudo: false
group: edge
language: python
python: 3.6
install: pip install .
env:
  - TEST="score dm.edm.json"
  - TEST="score eds.edm.json"
  - TEST="score eds.smatch.json"
  - TEST="score eds.mrp.json"
  - TEST="score dm.sdp.json"
  - TEST="score ucca.ucca.json"
  - TEST="score ucca.smatch.json"
  - TEST="score ucca.mrp.json"
  - TEST="score test.smatch.json"
  - TEST="score coli.smatch.json"
  - TEST="score coli.mrp.json"
  - TEST="score unit"
  - TEST="sample all"
  - TEST="validate all"
script:
  - make -C data/$TEST
